language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t stefanias98/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true stefanias98/docker-react-app npm run test -- --coverage